import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const roboto = localFont({
  src: "../public/fonts/robotofont.ttf", // path is relative to THIS file
  weight: "400",
  style: "normal",
  variable: "--font-roboto", // optional
  display: "swap",
});

export const archivi = localFont({
  src: "../public/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf", // path is relative to THIS file
  weight: "400",
  style: "normal",
  variable: "--font-archive", // optional
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${archivi.variable} font-normal`}>
      <body>{children}</body>
    </html>
  );
}
